{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reformulas
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reformulas_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reformulas/reformulas_{{ version }}.tar.gz
  sha256: b0ea03e8d55ac9c718deebda4cb92a72e760490ea4adb93741d712de81441b5d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rdpack
  run:
    - r-base
    - r-matrix
    - r-rdpack

test:
  commands:
    - $R -e "library('reformulas')"           # [not win]
    - "\"%R%\" -e \"library('reformulas')\""  # [win]

about:
  home: https://github.com/bbolker/reformulas
  license: GPL-3.0-only
  summary: Takes formulas including random-effects components (formatted as in 'lme4', 'glmmTMB',
    etc.) and processes them. Includes various helper functions.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
